name: publish
on: [push]
jobs:
  publish-samba-domain-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Login To Github
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the samba-domain Docker image
      run: |
        docker build . --tag ghcr.io/dumaresq/samba-domain:latest
        docker push ghcr.io/dumaresq/samba-domain:latest
