name: publish
on: [push]
jobs:
publish-samba-domain-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
- name: Build the samba-domain Docker image
run: |
       docker build . --tag ghcr.io/dumaresq/samba-domain:latest
       docker run ghcr.io/dumaresq/samba-domain:latest
       docker push ghcr.io/dumaresq/samba-domain:latest
